use_frameworks!

target 'PeripheralMenu_Example' do
  pod 'PeripheralMenu', :path => '../'

  target 'PeripheralMenu_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
